version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: csv_processor_app
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - build-assets:/var/www/html/public/build
            - ./docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        depends_on:
            - mysql

    webserver:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: csv_processor_server
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - build-assets:/var/www/html/public/build
        ports:
            - "7000:80"
        depends_on:
            - app
            - redis
    
    redis:
        image: redis:alpine
        container_name: csv_processor_redis
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data


    mysql:
        image: mysql:8.0
        container_name: csv_processor_db
        environment:
            MYSQL_DATABASE: db_csv
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: your_password
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    build-assets:
    mysql_data:
    redis_data:
